"""Auto-discover cameras and AI-pick their configuration.

This is the zero-config onboarding path (v0.3.11+). Replaces the
hand-written ``adapters: []`` YAML for the common case. The user just
installs the add-on, leaves ``auto_discover: true`` set (the default),
and SentiHome:

1. Lists every HA camera entity via :meth:`HATools.discover_ha_cameras`.
2. Skips entities in ``state in {unavailable, unknown}``.
3. Groups entities by physical device (shared device-tokens — see
   :func:`group_by_device`).
4. Picks ONE stream per device using a preference order tuned from
   what we've learned in v0.3.x bring-up:
     - Prefer Reolink ``_fluent`` (sub) over ``_clear`` (main) —
       verified: ``_fluent`` snapshot is a real 97 KB JPEG.
     - Exclude Reolink ``_profile*`` (ONVIF mainstream entity, returns
       login HTML on this firmware).
     - Exclude Dahua ``_sub_2``, ``_sub_3`` (duplicate sub streams).
5. Picks motion sensors using a whitelist: prefer
   ``_smart_motion_human``, ``_person_detection``, etc. over generic
   ``_motion_alarm`` (noisy — fires on pool ripples + leaves).
6. Cooldown defaults to 10 s.

Per-device overrides (enable/disable, stream, motions, cooldown) live in
``/data/sentihome/adapter_overrides.json`` (loaded by :mod:`.overrides`)
and merge over the AI picks. The ``/ha_cameras`` Web UI card writes
overrides via POST endpoints, eliminating YAML editing entirely.

Output is a list of :class:`DiscoveryDecision`, each carrying the AI
pick + all candidate streams/motions so the UI can render override
controls.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:
    from sentihome_ha_agent.mcp_tools import HACameraEntity

logger = structlog.get_logger(__name__)


# ─── stream preference ────────────────────────────────────────────────
# Lower index = preferred. Ranked low-bandwidth-first because:
#   (a) snapshots are cheaper to fetch on substreams;
#   (b) Reolink's _profile000_mainstream is broken (auth issue) and we
#       don't even want to RANK it — see _STREAM_EXCLUDE_PATTERNS below.
# Match is "ends with _{hint}" OR "_{hint}_" appears in the slug.

_STREAM_PREFERENCE = (
    "fluent",  # Reolink sub stream (verified working)
    "sub",  # Dahua / generic sub stream
    "low",  # generic low-res
    "low_res",
    "main",  # Dahua main (verified working) / generic main
    "mainstream",
    "clear",  # Reolink main
    "high",  # generic high-res
    "high_res",
)

# Hard exclusions — never even consider these streams.
_STREAM_EXCLUDE_PATTERNS = (
    "_profile",  # ONVIF mainstream: returns login HTML on Reolink
    "_sub_2",  # Dahua duplicate sub stream (3 sub streams advertised
    "_sub_3",  # but we only need 1)
    "_sub_4",
)


# ─── motion-sensor preference ────────────────────────────────────────
# Goal: pick AI-classified sensors so the alert headline can say
# "Person at pool cam" instead of "Motion at pool cam". The generic
# ``motion_alarm`` fires on every leaf, ripple, and shadow — exclude.

# AI-classified sensors (highest priority).
_MOTION_AI_KEYWORDS = (
    "smart_motion_human",
    "smart_motion_vehicle",
    "smart_motion_animal",
    "person_detection",
    "vehicle_detection",
    "pet_detection",
    "animal_detection",
    "package_detection",
    "intrusion_area",  # Reolink per-zone intrusion sensors
)

# Fallback tier — used when no AI sensors are present on the device.
# These are still classification-ish (Reolink exposes _person /
# _vehicle / _animal as plain sensors when AI is enabled).
_MOTION_FALLBACK_KEYWORDS = (
    "_person",
    "_vehicle",
    "_animal",
    "_pet",
    "_package",
)

# Hard exclusions — noisy or duplicates.
_MOTION_EXCLUDE_KEYWORDS = (
    "motion_alarm",  # fires on leaves, shadows, ripples
    "video_motion_info",  # legacy video motion (Dahua)
    "cell_motion_detection",  # Reolink cell-grid motion (very noisy)
)

DEFAULT_COOLDOWN_SECONDS = 10.0


@dataclass(frozen=True)
class DiscoverySpec:
    """One camera that should run a :class:`HACameraLoop`.

    Generated by auto-discovery + override merge. Maps 1:1 to
    :class:`HACameraLoop` constructor args. ``device_id`` is stable
    across stream re-picks so per-device override state survives an
    AI stream change.
    """

    device_id: str
    """Stable identifier for this physical device, derived from
    :func:`group_by_device`. Used as ``camera_id`` for
    :class:`HACameraLoop`."""

    camera_entity: str
    """The HA camera entity to fetch snapshots from."""

    friendly_name: str
    """Human-readable name for logs + alert headlines."""

    motion_entities: tuple[str, ...]
    """The ``binary_sensor.*`` entities to subscribe to."""

    cooldown_seconds: float = DEFAULT_COOLDOWN_SECONDS

    source: str = "auto"
    """``auto`` = pure AI pick; ``override`` = user overrode at least
    one field."""


@dataclass
class DiscoveryDecision:
    """Per-device discovery output, including all candidates for the UI.

    One :class:`DiscoveryDecision` per physical device. The UI iterates
    these to render an Enable/Disable + Override card per device.

    ``enabled=True`` means a :class:`DiscoverySpec` is active and a
    camera loop is running. ``enabled=False`` means the user disabled
    it or it failed the health check; ``spec`` is None in that case.
    """

    device_id: str
    friendly_name: str
    enabled: bool
    spec: DiscoverySpec | None

    candidate_streams: list[str]
    """All HA camera entities discovered for this device, in
    preference order. The UI shows these as radio options."""

    candidate_motions: list[str]
    """All motion-like sensors heuristically matched to this device.
    The UI shows these as checkbox options."""

    auto_disabled_reason: str | None = None
    """When non-None, AI auto-disabled this device (e.g. all streams
    unavailable, or the chosen stream failed the snapshot health
    check). UI surfaces the reason; user can override manually."""

    motion_switches: list[dict[str, str]] | None = None
    """v0.3.16: HA ``switch.*motion*`` entities heuristically matched
    to this device (each ``{entity_id, friendly_name, state}``). When
    any are ``off``, the UI shows a banner + Turn-on button — common
    misconfig where the parent motion switch is off and so all
    binary_sensor.*_motion_* stay off too."""

    suggest_generic_motion: str | None = None
    """v0.3.16: when AI-only sensors are picked and a ``_motion_alarm``
    is among the candidates, this holds that entity_id so the UI can
    offer a one-click "Use generic motion alarm" override. Useful
    when AI sensors stay silent (e.g. Dahua Smart Plan not
    configured)."""


# ─── device grouping ─────────────────────────────────────────────────


def group_by_device(
    cameras: list[HACameraEntity],
) -> dict[str, list[HACameraEntity]]:
    """Group camera entities by physical device.

    Two cameras with the same "device tokens" (slug split on _, with
    stream/stop tokens dropped) are treated as the same device.

    Examples:
      camera.dahuapoolcam_main + camera.dahuapoolcam_sub
        → device tokens {'dahuapoolcam'} → same device
      camera.front_south_camera_fluent +
      camera.front_south_camera_profile000_mainstream
        → device tokens {'front', 'south'} → same device

    Cameras with no meaningful tokens (e.g. ``camera.cam_1``) each get
    their own group keyed off the full slug, to avoid accidentally
    merging unrelated cameras.

    Returns ``{device_id: [entity, ...]}``. ``device_id`` is the joined
    sorted token list (e.g. ``"front_south"``, ``"dahuapoolcam"``).
    """
    # Import locally to avoid circulars and to reuse mcp_tools' existing
    # token logic — already well-tuned for stripping stream suffixes.
    from sentihome_ha_agent.mcp_tools import _meaningful_tokens

    groups: dict[str, list[HACameraEntity]] = {}
    for cam in cameras:
        slug = cam.camera_entity.removeprefix("camera.")
        tokens = _meaningful_tokens(slug)
        if tokens:
            device_id = "_".join(sorted(tokens))
        else:
            # No tokens → fall back to the full slug so unrelated
            # tokenless cameras don't accidentally merge.
            device_id = slug
        groups.setdefault(device_id, []).append(cam)
    return groups


# ─── stream + motion pickers (the AI heuristics) ─────────────────────


def _stream_excluded(entity_id: str) -> bool:
    return any(pat in entity_id for pat in _STREAM_EXCLUDE_PATTERNS)


def pick_stream(streams: list[HACameraEntity]) -> HACameraEntity | None:
    """Pick the best stream from a device's available cameras.

    Filters out unavailable + excluded patterns, then sorts by
    :data:`_STREAM_PREFERENCE`. Ties broken alphabetically (deterministic
    for tests).

    Returns None if no usable stream exists — caller should mark the
    device as auto-disabled with reason "no usable stream".
    """
    usable = [
        s
        for s in streams
        if s.state not in ("unavailable", "unknown") and not _stream_excluded(s.camera_entity)
    ]
    if not usable:
        return None

    def rank(cam: HACameraEntity) -> tuple[int, str]:
        eid = cam.camera_entity
        for i, hint in enumerate(_STREAM_PREFERENCE):
            if eid.endswith(f"_{hint}") or f"_{hint}_" in eid:
                return (i, eid)
        return (len(_STREAM_PREFERENCE), eid)

    usable.sort(key=rank)
    return usable[0]


def pick_motions(motion_candidates: list[str]) -> list[str]:
    """Pick motion sensors from a device's discovered candidates.

    Preference order:
      1. AI-classified sensors (smart_motion_*, *_detection, intrusion_*)
      2. Fallback classification sensors (_person, _vehicle, _animal)
      3. Anything left that isn't on the noise blacklist

    Always excludes ``motion_alarm``, ``video_motion_info``,
    ``cell_motion_detection`` (too noisy — false-positive prone).

    Returns a sorted list so output is deterministic for tests.
    """
    eligible = [m for m in motion_candidates if not any(ex in m for ex in _MOTION_EXCLUDE_KEYWORDS)]

    ai = [m for m in eligible if any(kw in m for kw in _MOTION_AI_KEYWORDS)]
    if ai:
        return sorted(ai)

    fallback = [m for m in eligible if any(kw in m for kw in _MOTION_FALLBACK_KEYWORDS)]
    if fallback:
        return sorted(fallback)

    # Last resort: any motion sensor that isn't excluded. Better to
    # alert on something than nothing.
    return sorted(eligible)


def _first_friendly_name(cams: list[HACameraEntity]) -> str:
    """Pick a clean human-readable name from a device's cameras."""
    for c in cams:
        if c.friendly_name:
            return c.friendly_name
    return cams[0].camera_entity.removeprefix("camera.")


# ─── top-level: combine grouping + heuristics + overrides ─────────────


def build_decisions(
    cameras: list[HACameraEntity],
    overrides: dict[str, dict] | None = None,
) -> list[DiscoveryDecision]:
    """Produce one :class:`DiscoveryDecision` per physical device.

    Merges AI picks with user overrides. The ``/ha_cameras`` UI iterates
    this list to render the per-device card.

    ``overrides`` shape (loaded from :func:`.overrides.load_overrides`):

      .. code-block:: json

         {
           "front_south": {
             "enabled": true,
             "stream_override": "camera.front_south_camera_fluent",
             "motion_override": ["binary_sensor.front_south_person"],
             "cooldown_override": 15.0
           },
           "front_south_profile_ONVIF_broken_one": {"enabled": false}
         }

    Override fields are independent — supplying any one of stream /
    motion / cooldown leaves the others as AI picks.

    Returns a list sorted by device_id for deterministic UI ordering.
    """
    overrides = overrides or {}
    decisions: list[DiscoveryDecision] = []

    grouped = group_by_device(cameras)
    for device_id, cams in sorted(grouped.items()):
        # All candidate options for the UI — show everything we know
        # about, so the user can override even excluded entries if
        # they really want to.
        candidate_streams = sorted(c.camera_entity for c in cams)
        all_motions: set[str] = set()
        for c in cams:
            all_motions.update(c.motion_candidates)
        candidate_motions = sorted(all_motions)
        friendly = _first_friendly_name(cams)

        ov = overrides.get(device_id, {})

        # Explicit user-disabled → render as disabled, no spec.
        if ov.get("enabled") is False:
            decisions.append(
                DiscoveryDecision(
                    device_id=device_id,
                    friendly_name=friendly,
                    enabled=False,
                    spec=None,
                    candidate_streams=candidate_streams,
                    candidate_motions=candidate_motions,
                )
            )
            continue

        # Determine the chosen stream: override wins, else AI pick.
        stream_ov = ov.get("stream_override")
        if stream_ov:
            chosen_stream_id: str | None = stream_ov
        else:
            ai_stream = pick_stream(cams)
            chosen_stream_id = ai_stream.camera_entity if ai_stream else None

        if chosen_stream_id is None:
            # No usable stream + no override → auto-disable.
            decisions.append(
                DiscoveryDecision(
                    device_id=device_id,
                    friendly_name=friendly,
                    enabled=False,
                    spec=None,
                    candidate_streams=candidate_streams,
                    candidate_motions=candidate_motions,
                    auto_disabled_reason=(
                        "no usable stream — all entities are unavailable or excluded"
                    ),
                )
            )
            continue

        motion_ov = ov.get("motion_override")
        if motion_ov:
            chosen_motions: tuple[str, ...] = tuple(sorted(motion_ov))
        else:
            chosen_motions = tuple(pick_motions(sorted(all_motions)))

        cooldown = float(ov.get("cooldown_override", DEFAULT_COOLDOWN_SECONDS))

        source = "override" if (stream_ov or motion_ov or "cooldown_override" in ov) else "auto"

        spec = DiscoverySpec(
            device_id=device_id,
            camera_entity=chosen_stream_id,
            friendly_name=friendly,
            motion_entities=chosen_motions,
            cooldown_seconds=cooldown,
            source=source,
        )

        # v0.3.16: if the chosen motion entities are all AI-classified
        # (smart_motion_human, _person_detection, etc.) AND a generic
        # _motion_alarm exists in the candidate pool, suggest it as a
        # one-click fallback. This catches the common Dahua trap where
        # the camera's Smart Plan isn't configured so AI sensors stay
        # silent — but motion_alarm still fires.
        suggest_generic: str | None = None
        all_chosen_are_ai = bool(chosen_motions) and all(
            any(kw in m for kw in _MOTION_AI_KEYWORDS) for m in chosen_motions
        )
        if all_chosen_are_ai:
            for m in candidate_motions:
                if "motion_alarm" in m:
                    suggest_generic = m
                    break

        decisions.append(
            DiscoveryDecision(
                device_id=device_id,
                friendly_name=friendly,
                enabled=True,
                spec=spec,
                candidate_streams=candidate_streams,
                candidate_motions=candidate_motions,
                suggest_generic_motion=suggest_generic,
            )
        )

    return decisions
